# The URL the site will be built for
base_url = "https://heinen.dev"
title = "Teddy Heinen"
generate_feed = true

compile_sass = true
build_search_index = true

taxonomies = [
    {name = "tags", rss = true},
    {name = "categories", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"

[extra]
# Put all your custom variables here
anpu_date_format="%e %B %Y"
anpu_menu_links = [
    { url = "$BASE_URL/about/", name = "About" },
    { url = "$BASE_URL/tags/", name = "Tags" },
]
